fix: fix
Idein/actcast-app-examples pull request #24
Opened 2024-10-31 08:07 UTC by tawashichan

2024-11-01 06:25 UTC, legokichi commented on amazon-kinesis-video-streams/manifesto/bullseye.json
> +      "type": "framebuffer"
require: false いります？

2024-11-01 06:26 UTC, legokichi commented on amazon-kinesis-video-streams/.actdk/setting.json
> +  "app_server_id": 53,
todo

2024-11-01 06:26 UTC, legokichi commented on amazon-kinesis-video-streams/.actdk/dependencies.json
> +      "actfw-core==2.7.0",
update

2024-11-01 06:43 UTC, legokichi commented on amazon-kinesis-video-streams/Dockerfile
> +RUN git checkout v3.4.2
updated

2024-11-05 04:49 UTC, legokichi commented on amazon-kinesis-video-streams/manifesto/bullseye.json
> +      "type": "framebuffer"
pi4にはない

2024-11-05 05:46 UTC, legokichi commented on amazon-kinesis-video-streams/README.md
> +cp /opt/bullseye/*.so /workspace/bullseye/
```
cp -r /opt/bullseye/ /workspace/
```

2024-11-05 10:26 UTC, legokichi commented on amazon-kinesis-video-streams/.actdk/dependencies.json
> +      "gstreamer1.0-omx",
h264enc がない

2024-11-05 10:38 UTC, legokichi commented on amazon-kinesis-video-streams/app/kvs.py
> +                "x264enc",
ハードウェアエンコーダがみつからないので代用

2024-11-05 10:38 UTC, legokichi commented on amazon-kinesis-video-streams/.actdk/dependencies.json
> +      "libgstreamer1.0-dev",
最小構成わからないから全部入れる

2024-11-05 10:39 UTC, legokichi commented on amazon-kinesis-video-streams/app/main.py
> +        cap = UnicamIspCapture(
UnicamIspCapture への対応方法わからないからオプションを消す

2024-11-14 08:49 UTC, legokichi commented on amazon-kinesis-video-streams/manifesto/bullseye.json
> +  "allow_all_networks": true
todo

2024-11-14 09:48 UTC, legokichi commented on amazon-kinesis-video-streams/manifesto/bullseye.json
> +        "/dev/v4l-subdev0"
actcast-writer ではこれがない fmv にはある

2024-11-18 07:09 UTC, legokichi commented on amazon-kinesis-video-streams/app/main.py
> +                preview_area, (CAPTURE_WIDTH, CAPTURE_HEIGHT), 16
https://idein-inc.slack.com/archives/CK59GN25R/p1731913687705129 を読む限りユニークであれば 2000 から変えなくても良さそう

2024-11-18 07:10 UTC, legokichi commented on amazon-kinesis-video-streams/setting_schema.json
> -    "exposure_time": {
https://actcast.io/docs/ja/ApplicationDevelopment/ForActcastOS3/#%e3%81%9d%e3%81%ae%e4%bb%96%e3%81%ae%e6%b3%a8%e6%84%8f%e7%82%b9
露光調整はできなくなった

2024-11-18 07:10 UTC, garasubo requested changes

2024-11-18 07:10 UTC, garasubo commented on amazon-kinesis-video-streams/README.md
> +password は raspberry です
passwordはpi imagerで書き込んだときのユーザー設定のものなのでrapsberryじゃないです

2024-11-18 07:10 UTC, garasubo commented on amazon-kinesis-video-streams/README.md
> +rsync -e ssh pi@<REMOTE>:/home/pi/workspace/*.so ./app/
この方法ではrsyncできず、元の例のように一つ一つファイルを指定する必要があります

2024-11-18 07:10 UTC, garasubo commented on amazon-kinesis-video-streams/README.md
>  password は raspberry です
ここも同様

2024-11-18 07:11 UTC, legokichi commented on amazon-kinesis-video-streams/app/main.py
> +                preview_area, (CAPTURE_WIDTH, CAPTURE_HEIGHT), 16
> layer must be between 1 and 16

でした

2024-11-18 07:27 UTC, legokichi commented on amazon-kinesis-video-streams/setting_schema.json
> -        "ja": "撮影画像の回転(0, 180 のどれか)"
vflip

2024-11-18 07:42 UTC, legokichi commented on amazon-kinesis-video-streams/README.md
> +rsync -e ssh pi@<REMOTE>:/home/pi/workspace/*.so ./app/
`\*.so` にします

2024-11-18 07:48 UTC, legokichi commented on amazon-kinesis-video-streams/setting_schema.json
> +    "aws_secret_access_key"
required 変更

2024-11-18 08:22 UTC, legokichi commented on amazon-kinesis-video-streams/manifesto/bullseye.json
> +    "RSPi3BPlus",
3b+ 動作確認済み

2024-11-18 08:27 UTC, garasubo approved these changes
動作確認もしたので良いと思います

2024-11-18 09:04 UTC, legokichi commented on amazon-kinesis-video-streams/.actdk/setting.json
> +  "app_server_id": 53,
```suggestion
  "app_server_id": 1,
```

2024-11-18 09:06 UTC, merged